### ISSUE TITLE
General: When saving, can't tell when it is done

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#242]
When there are changes that need saving, the app shows the save button.
On click, the save button has an often brief progress indicator, then disappears.
Testers have not considered this sufficient feedback, and are looking for a better way to know that the series or story has saved.

Some ideas are a simple message at top that disappears in a few seconds, or leaving the saved button there but now disabled (but breaks material design paradigm), or updating and highlighting the last saved time to indicate the save is complete.

**Comment by kookster** [comment]
more comments:
"I expect some kind of confirmation that it is done and live, like a tiny banner, saying it will be up in the store in a little while

After hitting story create, didn't know if that meant I needed to do the other tabs or could just hit publish."

**Comment by kookster** [comment]
could also include a scroll to top, see other ticket for this...

**Comment by cavis** [comment]
Trying to avoid cluttering the page with more feedback-text.  Some ideas:

### (A)

Just [show a disabled "Saved" button](http://cav.is/s/xl6it.gif) after the save completes.  Gives just enough feedback.

Downside is that it's a bit jarring to see the Publish button replace the Discard one.  And this kind of feedback wouldn't work for Publish/Unpublish, which swap each other out as you take those actions.

Which got me thing about...

### (B)

Maybe it's time to add a full-fledged [WP style status box](http://cav.is/s/etqje.jpg).  We can use this to give more advanced feedback on if/when the story is published.  Could also give a bit more info on validation errors, and work left TODO before the story can be published.

In this world, the toolbar would only contain the Save/Saved and Discard buttons.  And the date in the toolbar would just be last-saved-date, not published-at.  Since we're now displaying that in the status box.

### (C)

Crazy idea: some sort of [expander in the toolbar](http://cav.is/s/viafi.gif) to show/hide the more advanced buttons (Publish, Unpublish, Delete).  Could also do this as a bootstrap-style dropdown.  But I liked this slide-out more.

**Comment by sandikbarr** [comment]
I like the WP style status box. Can the background be `#ddd` rather than white to differentiate from the tabs and set it apart as supplemental information?
