### ISSUE TITLE
Investigate angry missing image from test series

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#301]
May be from processing failing
May be from error trying to upload incorrect size file
(Try uploading other image types to reproduce)

**Comment by sandikbarr** [comment]
Can't seem to recreate this
* It won't upload a file without proper exif data because of the min WxH restrictions. 
* removing most of an image file but retaining the exif data still interpreted as an image (aint even a little bit mad)
* create double click doesn't seem to have any affect
* Save double click resulted in a deadlock error on double POSTing the image but no angry image

**Comment by sandikbarr** [comment]
I've got angry images now that were showing up as the images I had set previously. One likely cause is that I had navigated away before the processing progress bar was finished.

**Comment by cavis** [comment]
@sandikbarr just read this.

The "Processing progress bar" is totally fake.  It just moves along for a set number of seconds, polling CMS for `image.status === "completed"`.  So navigating away shouldn't make a difference.

Can you verify if these images are 0-byte?  One bug I've seen is:

1. You upload the image to the temp S3 bucket.  It displays fine, GET-ing it from that temp bucket.
2. You save, and the image lambda kicks off.  As long as `image.status !== "complete"`, you're still seeing the temp bucket image.
3. Image lambda completes, but for some reason writes a 0-byte file to the final bucket.  Now your browser pulls that image and you get an error.

**Comment by sandikbarr** [comment]
Yes, response to the image request is zero length.
