### ISSUE TITLE
Delete episodes that are not published

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#339]

**Comment by sandikbarr** [comment]
This is what has been merged, but we need to figure out proper placement for buttons:
<img width="409" alt="screen shot 2017-02-02 at 11 19 03 am" src="https://cloud.githubusercontent.com/assets/2250413/22562765/88024930-e943-11e6-929a-875492a26658.png">

@cavis vote is that we always hide the Delete button under the Edit link, even for DRAFT. This is similar to wordpress. @cavis also has idea that we try putting the Publish button under the Edit link but always show the hidden buttons when ready to publish, would need to see in practice

@sandikbarr has idea that we use icon buttons in place of Edit link (font icons for now thinking we'll move to an svg icon set down the road) A trash icon button will always be shown for delete. Maybe a pencil instead of Edit, but edit feels a little weird on that too since it would then only be for toggling to unpublished.

@farski? @kookster?

**Comment by gcampo88** [comment]
closing this and moving the new conversation about general action button appearance in status box to #354
