### ISSUE TITLE
show frontend errors if validations fail on backend

### ISSUE THREAD

**Issue by sandikbarr** [PRX/publish.prx.org#422]
For series template total length, I entered 0:02:00 for the minimum and nothing for the maximum. I did not get any feedback from the UI that this was not valid. However, when saving the series template, there was a 500 error on the PUT to https://cms-staging.prx.tech/api/v1/audio_version_templates/416 with the message `Validation failed: Length minimum must be less than or equal to 0, Length maximum must be greater than or equal to 119`

While that error message doesn't exactly make sense and is not accurate for what is actually passing validation, front end validation should match what is allowed on the back end.

**Comment by gcampo88** [comment]
I think my vote here would be to alter this on the back end, since it's entirely reasonable to expect the user to set the length min and not the max. CMS ticket to handle: https://github.com/PRX/cms.prx.org/issues/322

But, we can leave this ticket here as one to show frontend errors if validations fail on backend?
